name: "Workflow"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate"

      - name: "Cache Composer packages"
        id: "composer-cache"
        uses: "actions/cache@v2.1.7"
        with:
          path: "vendor"
          key: "${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            "${{ runner.os }}-php-"

      - name: "Install dependencies"
        if: "steps.composer-cache.outputs.cache-hit != 'true'"
        run: "composer install --prefer-dist --no-progress --no-suggest"

  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.4.0"
      - uses: "php-actions/composer@v5"

      - name: "PHPUnit tests"
        uses: "php-actions/phpunit@v9"
        with:
          bootstrap: "vendor/autoload.php"
          configuration: "phpunit.xml"
